language: cpp

compiler: gcc

sudo: required

install: sudo apt-get update && sudo apt-get install build-essential &&
    sudo apt-get install libboost-dev &&
         sudo apt-get install libboost-all-dev && 
         wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz --notifications-check-certificate &&
         tar xf cmake-3.2.2.tar.gz &&
         cd cmake-3.2.2 &&
         ./configure &&
         make -j 8 &&
         sudo make install &&
         cmake --version &&
         pwd &&
         cd .. &&
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
         sudo apt-get update; sudo apt-get install gcc-4.8 g++-4.8 -y&
         gcc-4.8 --version &&
         which gcc-4.8

script: ./utils/build.sh

notifications:
  email:
    - xf1280@gmail.com
    - govinda.kamath@gmail.com
